allow resizing rect
codygo-solutions/magic-reviews-app pull request #8
Opened 2022-01-20 14:53 UTC by anshul01sharma

Rect with edit icon at the top left, once enters edit mode with appropriate UI dragged to resize & edit icon replace with OK button.

2022-01-20 15:50 UTC, danikenan requested changes
overall i am pleased. we are good. but we need some improvements.

pls extract the rectangle to its own widget (or set of widgets) and apply some naming conventions as well

whenever you feel like adding a comment, stop and ensure naming and code is properly named and partitioned.

2022-01-20 15:50 UTC, danikenan commented on lib/utils/resizable.dart
> +  // handle the gesture of pan start
use better names so no need for comments

2022-01-20 15:50 UTC, danikenan commented on lib/utils/resizable.dart
> +// Resizable class used for the dragging
Rename `Resizable` -> `ResizeHandle` and no need for comments

2022-01-20 15:50 UTC, danikenan commented on lib/utils/resizable.dart
> +  final Function onDrag;
private with `_` 
also add safer typing

2022-01-20 15:50 UTC, danikenan commented on lib/widgets/camera_view.dart
> +import 'package:magic_reviews_app/utils/resizable.dart';
use local relative path for local package

(yes... the line above too)

2022-01-20 15:50 UTC, danikenan commented on lib/widgets/camera_view.dart
> +  late double height, width, top, left;
unclear from naming that relates to focus rect

consider even extracting functionality of focus rect to its own widget

2022-01-20 15:50 UTC, danikenan commented on lib/widgets/camera_view.dart
> +  bool isEdit = false;
same

2022-01-20 15:50 UTC, danikenan commented on lib/widgets/camera_view.dart
> +            // Edit & Ok button as per the isEdit value
no comments. extract to build method/widget if unclear

2022-01-20 15:50 UTC, danikenan commented on lib/widgets/camera_view.dart
> +            // top left
extract to widget

2022-01-20 15:55 UTC, anshul01sharma commented on lib/utils/resizable.dart
> +  // handle the gesture of pan start
Okay, I will make the proper naming conventions.

2022-01-21 04:33 UTC, anshul01sharma commented on lib/utils/resizable.dart
> +  final Function onDrag;
regarding the return function callback it not allow underscore like this "_onDrag".

2022-01-21 06:27 UTC, merged